name: Deploy to PREPROD - Next.js

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ SECRETS_VM_KEY }}

      - name: Deploy to VM
        run: |
          ssh -t -o StrictHostKeyChecking=no ubuntu@${{ secrets.FRONTEND_VM_IP }} << 'EOF'
          cd ~/var/www/html
          git pull origin main
