name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VM_KEY }}  # Correct secret reference

      - name: Deploy to VM
        run: |
          ssh -t -o StrictHostKeyChecking=no ubuntu@${{ secrets.VM_IP }} << 'EOF'
          cd ubuntu/var/www/html  # Fixed the directory path
          git pull origin main
          EOF
